package com.SpringCommerce.models;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.parent_id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.parent_id
     *
     * @return the value of categories.parent_id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.parent_id
     *
     * @param parentId the value for categories.parent_id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.created_at
     *
     * @return the value of categories.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.created_at
     *
     * @param createdAt the value for categories.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.updated_at
     *
     * @return the value of categories.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.updated_at
     *
     * @param updatedAt the value for categories.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}