package com.SpringCommerce.models;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.email
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.password
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.full_name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.phone_number
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.gender
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.birthday
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.role
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_new.address
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.id
     *
     * @return the value of customer_new.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.id
     *
     * @param id the value for customer_new.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.email
     *
     * @return the value of customer_new.email
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.email
     *
     * @param email the value for customer_new.email
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.password
     *
     * @return the value of customer_new.password
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.password
     *
     * @param password the value for customer_new.password
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.full_name
     *
     * @return the value of customer_new.full_name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.full_name
     *
     * @param fullName the value for customer_new.full_name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.phone_number
     *
     * @return the value of customer_new.phone_number
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.phone_number
     *
     * @param phoneNumber the value for customer_new.phone_number
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.gender
     *
     * @return the value of customer_new.gender
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.gender
     *
     * @param gender the value for customer_new.gender
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.birthday
     *
     * @return the value of customer_new.birthday
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.birthday
     *
     * @param birthday the value for customer_new.birthday
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.created_at
     *
     * @return the value of customer_new.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.created_at
     *
     * @param createdAt the value for customer_new.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.updated_at
     *
     * @return the value of customer_new.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.updated_at
     *
     * @param updatedAt the value for customer_new.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.role
     *
     * @return the value of customer_new.role
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.role
     *
     * @param role the value for customer_new.role
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_new.address
     *
     * @return the value of customer_new.address
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_new.address
     *
     * @param address the value for customer_new.address
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }
}