package com.SpringCommerce.models;

import java.util.Date;

/**
 * @author vennd
 *
 */
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.alias
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.price
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.size
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String size;

    

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.short_description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String shortDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.quantity
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.deleted
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.feature
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Boolean feature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.image
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.categories
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String categories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.related_products
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    private String relatedProducts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.id
     *
     * @return the value of products.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.id
     *
     * @param id the value for products.id
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.name
     *
     * @return the value of products.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.name
     *
     * @param name the value for products.name
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.alias
     *
     * @return the value of products.alias
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.alias
     *
     * @param alias the value for products.alias
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.price
     *
     * @return the value of products.price
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.price
     *
     * @param price the value for products.price
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.size
     *
     * @return the value of products.size
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.size
     *
     * @param size the value for products.size
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.short_description
     *
     * @return the value of products.short_description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getShortDescription() {
        return shortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.short_description
     *
     * @param shortDescription the value for products.short_description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.quantity
     *
     * @return the value of products.quantity
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.quantity
     *
     * @param quantity the value for products.quantity
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.deleted
     *
     * @return the value of products.deleted
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.deleted
     *
     * @param deleted the value for products.deleted
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.feature
     *
     * @return the value of products.feature
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Boolean getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.feature
     *
     * @param feature the value for products.feature
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setFeature(Boolean feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.image
     *
     * @return the value of products.image
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.image
     *
     * @param image the value for products.image
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.created_at
     *
     * @return the value of products.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.created_at
     *
     * @param createdAt the value for products.created_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.updated_at
     *
     * @return the value of products.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.updated_at
     *
     * @param updatedAt the value for products.updated_at
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.description
     *
     * @return the value of products.description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.description
     *
     * @param description the value for products.description
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.categories
     *
     * @return the value of products.categories
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.categories
     *
     * @param categories the value for products.categories
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setCategories(String categories) {
        this.categories = categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.related_products
     *
     * @return the value of products.related_products
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public String getRelatedProducts() {
        return relatedProducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.related_products
     *
     * @param relatedProducts the value for products.related_products
     *
     * @mbg.generated Fri Apr 21 01:06:57 ICT 2023
     */
    public void setRelatedProducts(String relatedProducts) {
        this.relatedProducts = relatedProducts;
    }
    
    @Override
	public String toString() {
		return "Product [id=" + id + ", name=" + name + ", alias=" + alias + ", price=" + price + ", size=" + size
				+ ", shortDescription=" + shortDescription + ", quantity=" + quantity + ", deleted=" + deleted
				+ ", feature=" + feature + ", image=" + image + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt
				+ ", description=" + description + ", categories=" + categories + ", relatedProducts=" + relatedProducts
				+ "]";
	}
}